apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  labels:
    templates.weave.works/template-name: pipeline-notification-resources
    templates.weave.works/template-namespace: default
  name: podinfo
  namespace: flux-system
spec:
  address: http://blah/default/podinfo/dev
  secretRef: {}
  type: generic

---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  labels:
    templates.weave.works/template-name: pipeline-notification-resources
    templates.weave.works/template-namespace: default
  name: podinfo
  namespace: flux-system
spec:
  eventSeverity: info
  eventSources:
  - kind: HelmRelease
    name: podinfo
  exclusionList:
  - .*upgrade.*has.*started
  - .*is.*not.*ready
  - ^Dependencies.*
  providerRef:
    name: podinfo
