---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-fail
  namespace: flux-system
spec:
  targetNamespace: dev
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo
      version: '>15.0.0'
  interval: 1m0s
  releaseName: podinfo

