---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sources
  namespace: infra
spec:
  interval: 1m0s
  path: ./clusters/flux-demo/Infra
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

