---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: podinfo-dev
  namespace: flux-system
spec:
  interval: 30m0s
  url: https://github.com/stefanprodan/podinfo
  ref:
    branch: main

