---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: apps
  namespace: infra
spec:
  interval: 1m0s
  ref:
    branch: master
  url: https://github.com//stefanprodan/podinfo

