---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: podinfo
spec:
  interval: 5m0s
  path: ./
  prune: true
  sourceRef:
    kind: OCIRepository
    name: podinfo
    namespace: infra
  dependsOn:
    - name: sources.infra

